name: items_list
description: A new Flutter project.


publish_to: 'none'

version: 1.0.2+7

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  easy_localization: ^3.0.0
  get_it: ^7.2.0
  injectable: ^2.1.2
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.6

flutter:

  uses-material-design: true
  assets:
    - assets/strings/
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700